# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20160420_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.FaqCategory', verbose_name='Kategorie'),
        ),
    ]
