# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Titel')),
            ],
            options={
                'verbose_name': 'Artikel',
                'permissions': (('can_use', 'Wikikomponente nutzen'),),
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('timestamp', models.DateTimeField(verbose_name='Zeitstempel')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article', verbose_name='Zugehöriger Artikel')),
            ],
            options={
                'verbose_name': 'Artikelversion',
                'verbose_name_plural': 'Artikelversionen',
            },
        ),
    ]
