# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('staff', '0001_initial'), ('staff', '0002_auto_20160423_1817'), ('staff', '0003_auto_20160423_1834'), ('staff', '0004_auto_20160423_2058'), ('staff', '0005_auto_20160423_2058'), ('staff', '0006_auto_20160425_1334'), ('staff', '0007_auto_20160425_1344'), ('staff', '0008_auto_20160425_1345'), ('staff', '0009_remove_workshopcandidate_workshop_ideas'), ('staff', '0010_workshopcandidate_workshop_ideas'), ('staff', '0011_auto_20160427_2238'), ('staff', '0012_auto_20160501_1026'), ('staff', '0013_staffbarcode'), ('staff', '0014_stafftagbox'), ('staff', '0015_auto_20161109_2130'), ('staff', '0016_auto_20161110_0311'), ('staff', '0017_auto_20171016_2206'), ('staff', '0018_auto_20171016_2341'), ('staff', '0019_auto_20171019_2301')]

    initial = True

    dependencies = [
        ('ofahrtbase', '0019_auto_20161020_1750'),
        ('workshops', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('auth', '0008_alter_user_username_max_length'),
        ('ofahrtbase', '0012_auto_20160422_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Handynummer')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('orga_for', models.ManyToManyField(help_text='Hier kannst du eine oder mehrere Orgatätigkeiten auswählen, für die du dich interessierst.', to='auth.Group', verbose_name='Orgajob')),
                ('roommate_preference', models.CharField(blank=True, default='', max_length=255, verbose_name='Gewünschte Zimmernachbarn')),
            ],
            options={
                'abstract': False,
                'permissions': ('a', 'b'),
                'verbose_name': 'Orgabewerber',
                'verbose_name_plural': 'Orgabewerber',
            },
        ),
        migrations.CreateModel(
            name='WorkshopCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Handynummer')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('workshop_ideas', models.TextField(help_text='Bei mehreren Ideen, bitte eine Zeile pro Idee verwenden. Die Ideen sollen nur grob umrissen werden. Ein ausführlicherer Text wird erst an späterer Stelle benötigt.', verbose_name='Workshopidee(n)')),
                ('roommate_preference', models.CharField(blank=True, default='', max_length=255, verbose_name='Gewünschte Zimmernachbarn')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Workshopbewerber',
                'verbose_name_plural': 'Workshopbewerber',
                'permissions': (('group_full', 'Gruppe ist voll'),),
            },
        ),
        migrations.CreateModel(
            name='StaffBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv_barcode', models.IntegerField(blank=True, null=True, unique=True, verbose_name='KDV-Barcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTagBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=3, unique=True, verbose_name='Key')),
                ('text', models.CharField(max_length=10, unique=True, verbose_name='Text')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Tagbox',
                'verbose_name_plural': 'Tagboxen',
            },
        ),
        migrations.CreateModel(
            name='StaffRoomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Room', verbose_name='Zugeteilter Raum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
