# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('ofahrtbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email-Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Handynummer')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('orga_for', models.ManyToManyField(help_text='Hier kannst du eine oder mehrere Orgatätigkeiten auswählen, für die du dich interessierst.', to='auth.Group', verbose_name='Orgajob')),
            ],
            options={
                'verbose_name': 'Orgabewerber',
                'verbose_name_plural': 'Orgabewerber',
            },
        ),
        migrations.CreateModel(
            name='WorkshopCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email-Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Handynummer')),
                ('workshop_ideas', models.TextField(help_text='Bei mehreren Ideen, bitte eine Zeile pro Idee verwenden. Die Ideen sollen nur grob umrissen werden. Ein ausführlicherer Text wird erst an späterer Stelle benötigt.', verbose_name='Workshopidee(n)')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
            ],
            options={
                'verbose_name': 'Workshopbewerber',
                'permissions': (('group_full', 'Gruppe ist voll'),),
                'verbose_name_plural': 'Workshopbewerber',
            },
        ),
    ]
