# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_squashed_0019_auto_20171019_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgacandidate',
            options={'verbose_name': 'Orgabewerber', 'verbose_name_plural': 'Orgabewerber'},
        ),
        migrations.AlterField(
            model_name='orgacandidate',
            name='roommate_preference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gewünschte Zimmernachbarn'),
        ),
        migrations.AlterField(
            model_name='workshopcandidate',
            name='roommate_preference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gewünschte Zimmernachbarn'),
        ),
    ]
