# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='orga_for',
            field=models.ManyToManyField(
                blank=True,
                help_text=
                'Hier kannst du eine oder mehrere Orgatätigkeiten auswählen, für die du dich interessierst.',
                to='auth.Group',
                verbose_name='Orgajob'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='want_to_be_orga',
            field=models.BooleanField(
                help_text='Wähle diese Option aus um dich als Orga zu melden.',
                verbose_name='Orga'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='want_to_be_wl',
            field=models.BooleanField(
                help_text=
                'Wähle diese Option aus, wenn du einen oder mehrere Workshos anbieten möchtest.',
                verbose_name='Workshopanbieter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='workshop_ideas',
            field=models.TextField(
                blank=True,
                help_text=
                'Mehrere Ideen bitte in verschiedenen Zeilen unterbringen',
                verbose_name='Ideen für Workshops'),
        ),
    ]
