# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20180507_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopcandidate',
            name='base',
        ),
        migrations.DeleteModel(
            name='WorkshopCandidate',
        ),
    ]
