# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('ofahrtbase', '0012_auto_20160422_1430'),
        ('staff', '0002_auto_20160423_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email-Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Handynummer')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('orga_for', models.ManyToManyField(help_text='Hier kannst du eine oder mehrere Orgatätigkeiten auswählen, für die du dich interessierst.', to='auth.Group', verbose_name='Orgajob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email-Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Handynummer')),
                ('workshop_ideas', models.TextField(blank=True, help_text='Mehrere Ideen bitte in verschiedenen Zeilen unterbringen', verbose_name='Ideen für Workshops')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='base',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='orga_for',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
