# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20160423_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgacandidate',
            options={'permissions': ('a', 'b')},
        ),
    ]
