# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20160425_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopcandidate',
            name='workshop_ideas',
        ),
    ]
