# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        ('staff', '0009_remove_workshopcandidate_workshop_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcandidate',
            name='workshop_ideas',
            field=models.ManyToManyField(to='workshops.Workshop', verbose_name='Workshopideen'),
        ),
    ]
