# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20160427_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcandidate',
            name='workshop_ideas',
            field=models.TextField(help_text='Bei mehreren Ideen, bitte eine Zeile pro Idee verwenden. Die Ideen sollen nur grob umrissen werden. Ein ausführlicherer Text wird erst an späterer Stelle benötigt.', verbose_name='Workshopidee(n)'),
        ),
    ]
