# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0012_auto_20160501_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBarcode',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('kdv_barcode', models.IntegerField(
                    blank=True,
                    null=True,
                    unique=True,
                    verbose_name='KDV-Barcode')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
