# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('staff', '0013_staffbarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTagBox',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('letter', models.CharField(
                    max_length=3, unique=True, verbose_name='Key')),
                ('text', models.CharField(
                    max_length=10, unique=True, verbose_name='Text')),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='auth.Group')),
            ],
        ),
    ]
