# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_stafftagbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftagbox',
            name='group',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
