# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_auto_20171016_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgacandidate',
            name='roommate_preference',
            field=models.CharField(
                max_length=255,
                null=True,
                verbose_name='Gewünschte Zimmernachbarn'),
        ),
        migrations.AddField(
            model_name='workshopcandidate',
            name='roommate_preference',
            field=models.CharField(
                max_length=255,
                null=True,
                verbose_name='Gewünschte Zimmernachbarn'),
        ),
        migrations.AlterField(
            model_name='orgacandidate',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='E-Mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='workshopcandidate',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='E-Mail-Adresse'),
        ),
    ]
