# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofahrtbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Bezeichnung')),
                ('begin', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='Ende')),
                ('slottype', models.CharField(choices=[('workshop', 'Workshop'), ('event', 'Zentrale Veranstaltung'), ('food', 'Essen'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=30, verbose_name='Art des Slots')),
                ('priority', models.CharField(choices=[('opt', 'optional'), ('zentral', 'zentral'), ('dezentral', 'dezentral'), ('wichtig', 'wichtig')], default='zentral', max_length=30, verbose_name='Priorität')),
            ],
            options={
                'verbose_name': 'Zeitslot',
                'verbose_name_plural': 'Zeitslots',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('requirements', models.TextField(blank=True, verbose_name='Materialbedarf')),
                ('conditions', models.TextField(blank=True, verbose_name='Teilnahmebedingungen')),
                ('accepted', models.BooleanField(default=False, help_text='Workshopidee ist in Ordnung', verbose_name='Akzeptiert')),
                ('proved', models.BooleanField(default=False, help_text='Der aktuelle Workshopstand ist durch den Workshoporga geprüft.', verbose_name='Geprüft')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('host', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Workshopanbieter')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.Slot', verbose_name='Zugeteilter Zeitslot')),
            ],
            options={
                'verbose_name': 'Workshop',
                'permissions': (('can_use', 'Die Workshopkomponente nutzen'), ('editeveryworkshop', 'Jeden Workshop bearbeiten'), ('proveworkshop', 'Einen Workshop als geprüft markieren'), ('acceptworkshop', 'Einen Workshop als akzeptiert markieren'), ('assignworkshop', 'Workshopzuweisung ändern')),
                'verbose_name_plural': 'Workshops',
            },
        ),
    ]
