# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_participants',
            field=models.PositiveSmallIntegerField(blank=True, default=20, verbose_name='Maximale Teilnehmerzahl'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='miscellaneous',
            field=models.TextField(blank=True, help_text='Weitere Informationen zum Workshop', verbose_name='Sonstiges'),
        ),
    ]
