# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20160429_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='slot',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='workshops.Slot',
                verbose_name='Zugeteilter Zeitslot'),
        ),
    ]
