# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.Slot', verbose_name='Zugeteilter Zeitslot'),
        ),
    ]
