# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0013_remove_ofahrt_year'),
        ('workshops', '0005_auto_20160429_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='base',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt'),
            preserve_default=False,
        ),
    ]
