# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_workshop_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Workshopidee ist in Ordnung', verbose_name='Akzeptiert'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='proved',
            field=models.BooleanField(default=False, help_text='Der aktuelle Workshopstand ist durch den Workshoporga geprüft.', verbose_name='Geprüft'),
        ),
    ]
