# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_workshop_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='host',
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Workshopanbieter'),
        ),
    ]
