# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_workshop_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='conditions',
            field=models.TextField(
                blank=True, verbose_name='Teilnahmebedingungen'),
        ),
    ]
