# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_auto_20161009_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='otherstuff',
            field=models.TextField(blank=True, verbose_name='Sonstiges'),
        ),
    ]
