# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0023_auto_20161025_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 0, 0), verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 0, 0), verbose_name='Ende'),
        ),
    ]
