# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0031_auto_20171017_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'permissions': (('can_use', 'Die Workshopkomponente nutzen'), ('editeveryworkshop', 'Jeden Workshop bearbeiten'), ('proveworkshop', 'Einen Workshop als geprüft markieren'), ('acceptworkshop', 'Einen Workshop als akzeptiert markieren'), ('assignworkshop', 'Workshopzuweisung ändern'), ('viewemails', 'E-Mails der Workshopanbieter*innen einsehen')), 'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshops'},
        ),
    ]
