# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('ofahrtbase', '0001_initial'), ('ofahrtbase', '0002_ofahrt'), ('ofahrtbase', '0003_auto_20160419_2126'), ('ofahrtbase', '0004_auto_20160419_2154'), ('ofahrtbase', '0005_auto_20160419_2204'), ('ofahrtbase', '0006_auto_20160419_2222'), ('ofahrtbase', '0007_auto_20160419_2228'), ('ofahrtbase', '0008_room_number'), ('ofahrtbase', '0009_auto_20160419_2316'), ('ofahrtbase', '0010_auto_20160420_0040'), ('ofahrtbase', '0011_auto_20160422_1347'), ('ofahrtbase', '0012_auto_20160422_1430'), ('ofahrtbase', '0013_remove_ofahrt_year'), ('ofahrtbase', '0014_auto_20160908_2245'), ('ofahrtbase', '0015_auto_20161009_2033'), ('ofahrtbase', '0016_integersetting_stringsetting'), ('ofahrtbase', '0017_auto_20161020_1719'), ('ofahrtbase', '0018_ofahrt_self_participation'), ('ofahrtbase', '0019_auto_20161020_1750'), ('ofahrtbase', '0020_auto_20171016_2206'), ('ofahrtbase', '0021_auto_20171016_2341')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ofahrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, unique=True, verbose_name='Aktiv?')),
                ('begin_date', models.DateField(default=datetime.datetime(2016, 4, 19, 20, 28, 1, 436903, tzinfo=utc), verbose_name='Anreisedatum')),
                ('end_date', models.DateField(default=datetime.datetime(2016, 4, 19, 20, 28, 13, 459723, tzinfo=utc), verbose_name='Abreisedatum')),
                ('max_members', models.IntegerField(default=70, help_text='Dieser Wert bestimmt die maximale Größe der Festanmeldeliste.', verbose_name='Maximale Teilnehmendenzahl')),
                ('member_reg_open', models.BooleanField(default=False, help_text='Ist dieser Wert aktiviert, können sich Teilnehmer*innen registrieren.', verbose_name='Teilnehmeregistrierung')),
                ('orga_reg_open', models.BooleanField(default=False, help_text='Ist dieser Wert aktiviert, können sich Studierende als Ofahrtorga bewerben.', verbose_name='Orgaregistrierung')),
                ('queue_tolerance', models.IntegerField(default=20, help_text='Dieser Wert legt fest, ab wann Neuanmeldungen von Teilnehmer*innen in die Warteschlange müssen. (Warteschlange falls: aktuelle Festanmeldungen + aktuell vorläufige Anmeldungen > maximale Festanmeldungen + dieser Wert)', verbose_name='Warteschlangentoleranz')),
                ('workshop_reg_open', models.BooleanField(default=False, help_text='Ist dieser Wert aktiviert, werden derzeit Workshops gesucht.', verbose_name='Workshopregistrierung')),
                ('self_participation', models.IntegerField(default=2000, help_text='Eingenanteil der Teilnehmer*innen in Cent', verbose_name='Teilnahmebeitrag')),
            ],
            options={
                'verbose_name': 'Ofahrtobjekt',
                'verbose_name_plural': 'Ofahrtobjekte',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Gelände',
                'verbose_name_plural': 'Gelände',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('usecase_sleep', models.BooleanField(default=False, verbose_name='Schlafzimmer')),
                ('usecase_workshop', models.BooleanField(default=False, verbose_name='Aktivitätenraum')),
                ('usecase_outside', models.BooleanField(default=False, verbose_name='Freifläche')),
                ('usecase_store', models.BooleanField(default=False, verbose_name='Lagerraum')),
                ('usecase_meal', models.BooleanField(default=False, verbose_name='Speisesaal')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Building')),
                ('number', models.CharField(default=0, max_length=30)),
                ('capacity', models.IntegerField(default=0, help_text='Wieviele Teilnehmer*innen passen in diesen Raum?', verbose_name='Kapazität')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Location'),
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Gebäude', 'verbose_name_plural': 'Gebäude'},
        ),
    ]
