# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0001_squashed_0021_auto_20171016_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofahrt',
            name='begin_date',
            field=models.DateField(verbose_name='Anreisedatum'),
        ),
        migrations.AlterField(
            model_name='ofahrt',
            name='end_date',
            field=models.DateField(verbose_name='Abreisedatum'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
