# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0002_auto_20180507_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofahrt',
            name='workshop_reg_open',
        ),
    ]
