# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0004_auto_20160419_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to='ofahrtbase.Location'),
        ),
    ]
