# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0006_auto_20160419_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofahrt',
            name='begin_date',
            field=models.DateField(default=datetime.datetime(2016, 4, 19, 20, 28, 1, 436903, tzinfo=utc), verbose_name='Anreisedatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofahrt',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 4, 19, 20, 28, 13, 459723, tzinfo=utc), verbose_name='Abreisedatum'),
            preserve_default=False,
        ),
    ]
