# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0007_auto_20160419_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
