# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0008_room_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Gebäude', 'verbose_name_plural': 'Gebäude'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Tagungsort', 'verbose_name_plural': 'Tagungsorte'},
        ),
        migrations.AlterModelOptions(
            name='ofahrt',
            options={'verbose_name': 'Ofahrt', 'verbose_name_plural': 'Ofahrten'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Raum', 'verbose_name_plural': 'Räume'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Einstellung', 'verbose_name_plural': 'Einstellungen'},
        ),
    ]
