# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0009_auto_20160419_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofahrt',
            options={'verbose_name': 'Ofahrtobjekt', 'verbose_name_plural': 'Ofahrtobjekte'},
        ),
    ]
