# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0010_auto_20160420_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Gelände', 'verbose_name_plural': 'Gelände'},
        ),
        migrations.AddField(
            model_name='setting',
            name='readable',
            field=models.CharField(default='Bla', max_length=30, unique=True, verbose_name='Eigenschaft'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=30, unique=True, verbose_name='Schlüssel'),
        ),
    ]
