# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0012_auto_20160422_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofahrt',
            name='year',
        ),
    ]
