# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0014_auto_20160908_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='usecase_meal',
            field=models.BooleanField(
                default=False, verbose_name='Essensraum'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_outside',
            field=models.BooleanField(
                default=False, verbose_name='Freifläche'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_sleep',
            field=models.BooleanField(
                default=False, verbose_name='Schlafraum'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_store',
            field=models.BooleanField(default=False, verbose_name='Lagerraum'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_workshop',
            field=models.BooleanField(default=False, verbose_name='Workshops'),
        ),
    ]
