# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0015_auto_20161009_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegerSetting',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('key', models.CharField(
                    max_length=50, unique=True, verbose_name='Schlüssel')),
                ('readable', models.CharField(
                    max_length=50, unique=True, verbose_name='Eigenschaft')),
                ('value', models.IntegerField(verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Einstellung',
                'verbose_name_plural': 'Einstellungen (Zahlen)',
            },
        ),
        migrations.CreateModel(
            name='StringSetting',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('key', models.CharField(
                    max_length=50, unique=True, verbose_name='Schlüssel')),
                ('readable', models.CharField(
                    max_length=50, unique=True, verbose_name='Eigenschaft')),
                ('value', models.TextField(verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Einstellung',
                'verbose_name_plural': 'Einstellungen (Strings)',
            },
        ),
    ]
