# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0016_integersetting_stringsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofahrt',
            name='max_members',
            field=models.IntegerField(
                default=70,
                help_text=
                'Dieser Wert bestimmt die maximale Größe der Festanmeldeliste.',
                verbose_name='Maximale Teilnehmerzahl'),
        ),
        migrations.AddField(
            model_name='ofahrt',
            name='member_reg_open',
            field=models.BooleanField(
                default=False,
                help_text=
                'Ist dieser Wert aktiviert können sich Teilnehmer*innen registrieren.',
                verbose_name='Teilnehmeregistrierung'),
        ),
        migrations.AddField(
            model_name='ofahrt',
            name='orga_reg_open',
            field=models.BooleanField(
                default=False,
                help_text=
                'Ist dieser Wert aktiviert können sich Studierende als Ofahrtorga bewerben.',
                verbose_name='Orgaregistrierung'),
        ),
        migrations.AddField(
            model_name='ofahrt',
            name='queue_tolerance',
            field=models.IntegerField(
                default=20,
                help_text=
                'Dieser Wert legt fest ab wann Neuanmeldungen von Teilnehmer*innen in die Warteschlange müssen. (Warteschlange falls: aktuelle Festanmeldungen + aktuell vorläufige Anmeldungen > maximale Festanmeldungen + dieser Wert)',
                verbose_name='Warteschlangentolleranz'),
        ),
        migrations.AddField(
            model_name='ofahrt',
            name='workshop_reg_open',
            field=models.BooleanField(
                default=False,
                help_text=
                'Ist dieser Wert aktiviert werden derzeit Workshops gesucht.',
                verbose_name='Workshopregistrierung'),
        ),
    ]
