# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0017_auto_20161020_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofahrt',
            name='self_participation',
            field=models.IntegerField(default=2000, help_text='Eingenanteil der Teilnehmer*innen in Cent', verbose_name='Teilnahmebetrag'),
        ),
    ]
