# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0018_ofahrt_self_participation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegerSetting',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='StringSetting',
        ),
    ]
