# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofahrtbase', '0020_auto_20171016_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Wieviele Teilnehmer*innen passen in diesen Raum?', verbose_name='Kapazität'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_meal',
            field=models.BooleanField(default=False, verbose_name='Speisesaal'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_sleep',
            field=models.BooleanField(default=False, verbose_name='Schlafzimmer'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usecase_workshop',
            field=models.BooleanField(default=False, verbose_name='Aktivitätenraum'),
        ),
    ]
