# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('ofahrtbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zusammenfassung der Aufgabe', max_length=255, verbose_name='Aufgabe')),
                ('description', models.TextField(blank=True, help_text='Ausführlichere Beschreibung der Aufgabe (optional)', verbose_name='Beschreibung')),
                ('priority', models.CharField(choices=[('optional', 'optional'), ('unwichtig', 'unwichtig'), ('normal', 'normal'), ('wichtig', 'wichtig'), ('dringend', 'dringend')], default='normal', help_text='Die Priorität gibt an wie dringend das Ticket ist.', max_length=30, verbose_name='Priorität')),
                ('status', models.CharField(choices=[('neu', 'neu'), ('zugewiesen', 'zugewiesen'), ('erledigt', 'erledigt'), ('abgebrochen', 'abgebrochen')], default='neu', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingetragen am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Verändert am')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige OFahrt')),
            ],
            options={
                'verbose_name': 'Ticket',
                'permissions': (('can_use', 'Aufgabenverwaltung nutzen'),),
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Aufgabe')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('access_for', models.ManyToManyField(to='auth.Group', verbose_name='Zugang für')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Gib hier den Text an, den dein Kommentar enthalten soll.', verbose_name='Kommentartext')),
                ('timestamp', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Zugehöriges Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
        migrations.CreateModel(
            name='TaskHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('timestamp', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Zugehöriges Ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zugehöriger User')),
            ],
            options={
                'verbose_name': 'Historyeintrag',
                'verbose_name_plural': 'Historyeinträge',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(help_text='Über die Kategorie wird geregelt, welche Benutzer Zugriff auf dieses Ticket haben', on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskCategory', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='task',
            name='editors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Bearbeiter'),
        ),
    ]
