# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofahrtbase', '0013_remove_ofahrt_year'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=255, verbose_name='Aufgabe')),
                ('description', models.TextField(
                    blank=True, verbose_name='Beschreibung')),
                ('priority', models.CharField(
                    choices=[('optional', 'optional'),
                             ('unwichtig', 'unwichtig'), ('normal', 'normal'),
                             ('wichtig', 'wichtig'), ('dringend', 'dringend')],
                    max_length=30,
                    verbose_name='Priorität')),
                ('base', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='ofahrtbase.Ofahrt',
                    verbose_name='Zugehörige OFahrt')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=255, verbose_name='Aufgabe')),
                ('description', models.TextField(
                    blank=True, verbose_name='Beschreibung')),
                ('access_for', models.ManyToManyField(
                    to='auth.Group', verbose_name='Zugang für')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('timestamp', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('ticket', models.ForeignKey(
                    on_delete='Zugehöriges Ticket',
                    to='tasks.Task',
                    to_field='id')),
                ('user', models.ForeignKey(
                    on_delete='Autor',
                    to=settings.AUTH_USER_MODEL,
                    to_field='id')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
        migrations.CreateModel(
            name='TaskHistoryEntry',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('text', models.CharField(max_length=255,
                                          verbose_name='Text')),
                ('timestamp', models.DateField(verbose_name='Zeitpunkt')),
                ('ticket', models.ForeignKey(
                    on_delete='Zugehöriges Ticket',
                    to='tasks.Task',
                    to_field='id')),
            ],
            options={
                'verbose_name': 'Historyeintrag',
                'verbose_name_plural': 'Historyeinträge',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='tasks.TaskCategory',
                verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='task',
            name='editors',
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name='Bearbeiter'),
        ),
    ]
