# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160429_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('optional', 'optional'), ('unwichtig', 'unwichtig'), ('normal', 'normal'), ('wichtig', 'wichtig'), ('dringend', 'dringend')], default='normal', max_length=30, verbose_name='Priorität'),
        ),
    ]
