# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160429_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='editors',
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Bearbeiter'),
        ),
    ]
