# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160429_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('neu', 'neu'), ('zugewiesen', 'zugewiesen'),
                         ('erledigt', 'erledigt'), ('abgebrochen',
                                                    'abgebrochen')],
                default='neu',
                max_length=30,
                verbose_name='Status'),
        ),
    ]
