# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistoryentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zugehöriger User'),
        ),
    ]
