# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskhistoryentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistoryentry',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Zeitpunkt'),
        ),
    ]
