# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160429_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistoryentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zugehöriger User'),
        ),
    ]
