# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20160429_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(help_text='Über die Kategorie wird geregelt, welche Benutzer Zugriff auf dieses Ticket haben', on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskCategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Ausführlichere Beschreibung der Aufgabe (optional)', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Zusammenfassung der Aufgabe', max_length=255, verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('optional', 'optional'), ('unwichtig', 'unwichtig'), ('normal', 'normal'), ('wichtig', 'wichtig'), ('dringend', 'dringend')], default='normal', help_text='Die Priorität gibt an wie dringend das Ticket ist.', max_length=30, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(help_text='Gib hier den Text an, den dein Kommentar enthalten soll.', verbose_name='Kommentartext'),
        ),
    ]
