# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20160430_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': ('can_use', 'Aufgabenverwaltung nutzen'), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
