# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20160501_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_use', 'Aufgabenverwaltung nutzen'),), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
