# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tasks', '0012_auto_20160501_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='responsible_for',
            field=models.ManyToManyField(
                related_name='responsible',
                to='auth.Group',
                verbose_name='Hauptzuständige Gruppe'),
        ),
    ]
