# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_taskcategory_responsible_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='access_for',
            field=models.ManyToManyField(
                blank=True, to='auth.Group', verbose_name='Zugang für'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='responsible_for',
            field=models.ManyToManyField(
                blank=True,
                related_name='responsible',
                to='auth.Group',
                verbose_name='Hauptzuständige Gruppe'),
        ),
    ]
