# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('members', '0001_initial'), ('members', '0002_member_money_received'), ('members', '0003_auto_20160419_2018'), ('members', '0004_member_base'), ('members', '0005_auto_20160419_2222'), ('members', '0006_auto_20160419_2228'), ('members', '0007_auto_20160419_2316'), ('members', '0008_auto_20160419_2346'), ('members', '0009_auto_20160420_0000'), ('members', '0010_auto_20160422_1347'), ('members', '0011_member_is_really_ersti'), ('members', '0012_auto_20160427_1051'), ('members', '0013_person'), ('members', '0014_auto_20160428_0005'), ('members', '0015_auto_20160428_0018'), ('members', '0016_auto_20160503_1622'), ('members', '0017_auto_20160908_2136'), ('members', '0018_auto_20161015_1421'), ('members', '0019_auto_20161017_1638'), ('members', '0020_auto_20161020_1719'), ('members', '0021_member_kdv_barcode'), ('members', '0022_auto_20170602_2056'), ('members', '0023_auto_20171016_2206'), ('members', '0024_auto_20171016_2341'), ('members', '0025_remove_member_roommate_preference'), ('members', '0026_auto_20171019_2301')]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('ofahrtbase', '0013_remove_ofahrt_year'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('ofahrtbase', '0009_auto_20160419_2316'),
        ('ofahrtbase', '0003_auto_20160419_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Emailadresse')),
                ('birth_date', models.DateField(verbose_name='Geburtsdatum')),
                ('money_received', models.BooleanField(default=False, verbose_name='Geld eingegangen?')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('gender', models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume minderjähriger Teilnehmer verwendet.', max_length=1, verbose_name='Geschlecht')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('members', models.ManyToManyField(to='members.Member', verbose_name='Zugewiesene Personen')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Room', verbose_name='Zugehöriger Raum')),
            ],
            options={
                'verbose_name': 'Raumzuteilung',
                'verbose_name_plural': 'Raumzuteilungen',
            },
        ),
        migrations.AlterUniqueTogether(
            name='roomassignment',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume minderjähriger Teilnehmer verwendet.', max_length=25, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=180, unique=True, verbose_name='Emailadresse'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_really_ersti',
            field=models.BooleanField(default=False, verbose_name='Geprüft ob Ersti?'),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 27, 8, 51, 6, 78965, tzinfo=utc), verbose_name='Eingetragen am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 27, 8, 51, 18, 520378, tzinfo=utc), verbose_name='Verändert am'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FoodHandicaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=50, verbose_name='Lebensmittelunverträglichkeit')),
            ],
            options={
                'verbose_name': 'Lebensmittelunverträglichkeit',
                'verbose_name_plural': 'Lebensmittelunverträglichkeiten',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='food_preference',
            field=models.CharField(choices=[('normal', 'keine'), ('vegetarisch', 'vegetarisch'), ('vegan', 'vegan')], default='normal', max_length=30, verbose_name='Ernährungsgewohnheiten'),
        ),
        migrations.AddField(
            model_name='member',
            name='free_text',
            field=models.TextField(blank=True, verbose_name='Sonstige Anmerkungen'),
        ),
        migrations.AddField(
            model_name='member',
            name='food_handicaps',
            field=models.ManyToManyField(blank=True, help_text='Um Einträge abzuwählen, die STRG-Taste gedrückt halten und klicken.', to='members.FoodHandicaps', verbose_name='Sonstige Lebensmittelunverträglichkeiten'),
        ),
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Room', verbose_name='Zugeteilter Raum'),
        ),
        migrations.RemoveField(
            model_name='roomassignment',
            name='base',
        ),
        migrations.RemoveField(
            model_name='roomassignment',
            name='members',
        ),
        migrations.RemoveField(
            model_name='roomassignment',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomAssignment',
        ),
        migrations.AddField(
            model_name='member',
            name='queue',
            field=models.BooleanField(default=True, verbose_name='Warten auf Geldeingang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='queue_deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline für Geldeingang'),
        ),
        migrations.AlterField(
            model_name='member',
            name='money_received',
            field=models.BooleanField(default=False, verbose_name='Geld eingegangen? (Festangemeldet)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='money_received',
            field=models.BooleanField(default=False, verbose_name='Festangemeldet?'),
        ),
        migrations.AddField(
            model_name='member',
            name='kdv_barcode',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='KDV-Barcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=180, unique=True, verbose_name='E-Mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume minderjähriger Teilnehmer*innen verwendet.', max_length=25, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume verwendet.', max_length=25, verbose_name='Geschlecht'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
