# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Emailadresse')),
                ('birthday', models.DateField(verbose_name='Geburtsdatum')),
            ],
        ),
    ]
