# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofahrtbase', '0002_auto_20180507_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodHandicaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Lebensmittelunverträglichkeit')),
            ],
            options={
                'verbose_name': 'Lebensmittelunverträglichkeit',
                'verbose_name_plural': 'Lebensmittelunverträglichkeiten',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('gender', models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume verwendet.', max_length=25, verbose_name='Geschlecht')),
                ('email', models.EmailField(max_length=180, unique=True, verbose_name='E-Mail-Adresse')),
                ('birth_date', models.DateField(verbose_name='Geburtsdatum')),
                ('food_preference', models.CharField(choices=[('normal', 'keine'), ('vegetarisch', 'vegetarisch')], default='normal', max_length=30, verbose_name='Ernährungsgewohnheiten')),
                ('is_really_ersti', models.BooleanField(default=False, verbose_name='Geprüft ob Ersti?')),
                ('queue', models.BooleanField(verbose_name='Warten auf Geldeingang')),
                ('queue_deadline', models.DateTimeField(null=True, verbose_name='Deadline für Geldeingang')),
                ('money_received', models.BooleanField(default=False, verbose_name='Festangemeldet?')),
                ('kdv_barcode', models.IntegerField(blank=True, null=True, unique=True, verbose_name='KDV-Barcode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingetragen am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Verändert am')),
                ('free_text', models.TextField(blank=True, verbose_name='Sonstige Anmerkungen')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt')),
                ('food_handicaps', models.ManyToManyField(blank=True, help_text='Um Einträge abzuwählen, die STRG-Taste gedrückt halten und klicken.', to='members.FoodHandicaps', verbose_name='Sonstige Lebensmittelunverträglichkeiten')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Room', verbose_name='Zugeteilter Raum')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
            },
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
