# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_squashed_0026_auto_20171019_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodhandicaps',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Lebensmittelunverträglichkeit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='food_preference',
            field=models.CharField(choices=[('normal', 'keine'), ('vegetarisch', 'vegetarisch')], default='normal', max_length=30, verbose_name='Ernährungsgewohnheiten'),
        ),
    ]
