# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='money_received',
            field=models.BooleanField(
                default=False, verbose_name='Geld eingegangen?'),
        ),
    ]
