# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_money_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
