# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160419_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmer'},
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume minderjähriger Teilnehmer verwendet.', max_length=1, verbose_name='Geschlecht'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofahrtbase.Ofahrt', verbose_name='Zugehörige Ofahrt'),
        ),
    ]
