# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20160422_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_really_ersti',
            field=models.BooleanField(default=False, verbose_name='Geprüft ob Ersti?'),
        ),
    ]
