# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_is_really_ersti'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2016, 4, 27, 8, 51, 6, 78965, tzinfo=utc),
                verbose_name='Eingetragen am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2016, 4, 27, 8, 51, 18, 520378, tzinfo=utc),
                verbose_name='Verändert am'),
            preserve_default=False,
        ),
    ]
