# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20160428_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodHandicaps',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='food_preference',
            field=models.CharField(
                choices=[('normal', 'nein'), ('vegetarisch', 'Vegetarisch'),
                         ('vegan', 'Vegan')],
                default='normal',
                max_length=30,
                verbose_name='Vegetarier?'),
        ),
        migrations.AddField(
            model_name='member',
            name='free_text',
            field=models.TextField(
                blank=True, verbose_name='Sonstige Anmerkungen'),
        ),
        migrations.AddField(
            model_name='member',
            name='food_handicaps',
            field=models.ManyToManyField(
                to='members.FoodHandicaps',
                verbose_name='Sonstige Lebensmittelunverträglichkeiten'),
        ),
    ]
