# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20160428_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='food_handicaps',
            field=models.ManyToManyField(blank=True, to='members.FoodHandicaps', verbose_name='Sonstige Lebensmittelunverträglichkeiten'),
        ),
    ]
