# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20160908_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodhandicaps',
            options={'verbose_name': 'Lebensmittelunverträglichkeit', 'verbose_name_plural': 'Lebensmittelunverträglichkeiten'},
        ),
        migrations.AddField(
            model_name='foodhandicaps',
            name='text',
            field=models.CharField(default='', max_length=50, verbose_name='Lebensmittelunverträglichkeit'),
            preserve_default=False,
        ),
    ]
