# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20161015_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='queue',
            field=models.BooleanField(default=True, verbose_name='Warten auf Geldeingang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='queue_deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline für Geldeingang'),
        ),
        migrations.AlterField(
            model_name='member',
            name='money_received',
            field=models.BooleanField(default=False, verbose_name='Geld eingegangen? (Festangemeldet)'),
        ),
    ]
