# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20161017_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='food_handicaps',
            field=models.ManyToManyField(
                blank=True,
                help_text=
                'Um Einträge abzuwählen, die STRG-Taste gedrückt halten und Klicken.',
                to='members.FoodHandicaps',
                verbose_name='Sonstige Lebensmittelunverträglichkeiten'),
        ),
        migrations.AlterField(
            model_name='member',
            name='money_received',
            field=models.BooleanField(
                default=False, verbose_name='Festangemeldet?'),
        ),
    ]
