# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20161020_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kdv_barcode',
            field=models.IntegerField(
                blank=True, null=True, unique=True,
                verbose_name='KDV-Barcode'),
        ),
    ]
