# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20171016_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='food_preference',
            field=models.CharField(
                choices=[('normal', 'keine'), ('vegetarisch', 'vegetarisch'),
                         ('vegan', 'vegan')],
                default='normal',
                max_length=30,
                verbose_name='Ernährungsgewohnheiten'),
        ),
        migrations.AlterField(
            model_name='member',
            name='roommate_preference',
            field=models.CharField(
                max_length=255,
                null=True,
                verbose_name='Gewünschte Zimmernachbarn'),
        ),
    ]
