# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20171016_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='roommate_preference',
        ),
    ]
