# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_remove_member_roommate_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('n', 'keines der genannten')], default='n', help_text='Diese Angabe wird nur für die Zuteilung der Schlafräume verwendet.', max_length=25, verbose_name='Geschlecht'),
        ),
    ]
